services:
  redis:
    image: redis
  backend:
    build: ./backend
    depends_on:
      - redis

    environment:
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_DB: ${REDIS_DB:-0}

    ports:
      - "8000:8000"

  worker:
    build: ./worker
    depends_on:
      - redis

    environment:
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_DB: ${REDIS_DB:-0}
      OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY}
      OPENWEATHER_BASE_URL: ${OPENWEATHER_BASE_URL}
      OPENWEATHER_UNITS: ${OPENWEATHER_UNITS:-metric}
      OPENWEATHER_LANG: ${OPENWEATHER_LANG:-en}
      WEATHER_TTL_SECONDS: ${WEATHER_TTL_SECONDS:-300}
      FETCH_INTERVAL_SECONDS: ${FETCH_INTERVAL_SECONDS:-60}

  curl:
    image: curlimages/curl:8.6.0
    entrypoint: ["sleep", "3600"]
    depends_on:
      - backend