services:
  redis:
    image: redis
  backend:
    build: ./backend
    depends_on:
      - redis

    environment:
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_DB: ${REDIS_DB:-0}
      WEATHER_CITY: ${WEATHER_CITY:-Banska Bystrica}

    ports:
      - "8000:8000"

  worker:
    build: ./worker
    depends_on:
      - redis

    environment:
      REDIS_HOST: ${REDIS_HOST:-redis}
      REDIS_PORT: ${REDIS_PORT:-6379}
      REDIS_DB: ${REDIS_DB:-0}
      OPENWEATHER_API_KEY: ${OPENWEATHER_API_KEY}
      OPENWEATHER_BASE_URL: ${OPENWEATHER_BASE_URL}
      OPENWEATHER_UNITS: ${OPENWEATHER_UNITS:-metric}
      OPENWEATHER_LANG: ${OPENWEATHER_LANG:-en}
      WEATHER_TTL_SECONDS: ${WEATHER_TTL_SECONDS:-300}
      FETCH_INTERVAL_SECONDS: ${FETCH_INTERVAL_SECONDS:-60}
      WEATHER_CITY: ${WEATHER_CITY:-Banska Bystrica}

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    depends_on:
      - backend

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GF_ADMIN_USER:-admin}
      GF_SECURITY_ADMIN_USER: ${GF_ADMIN_PASSWORD:-admin}
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - prometheus

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend