{
 "title": "Weather Pipeline",
 "refresh": "15s",
 "panels": [
  {
   "title": "Total HTTP Requests",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "targets": [
    { "expr": "sum(http_requests_total)", "legendFormat": "Total Requests" }
   ]
  },
  {
   "title": "Requests per Endpoint",
   "type": "timeseries",
   "gridPos": { "x": 6, "y": 0, "w": 18, "h": 8 },
   "targets": [
    { "expr": "rate(http_requests_total[1m])", "legendFormat": "{{endpoint}}" }
   ]
  },
  {
   "title": "Cache Source Distributor",
   "type": "piechart",
   "gridPos": { "x": 0, "y": 4, "w": 6, "h": 8 },
   "targets": [
    {
     "expr": "sum by (source) (weather_cache_source_total)",
     "legendFormat": "{{source}}"
    }
   ]
  },
  {
   "title": "Requests Duration (p95)",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 12, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, endpoint))",
     "legendFormat": "p95 {{endpoint}}"
    }
   ]
  },
  {
   "title": "Requests Duration (p50)",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 12, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, endpoint))",
     "legendFormat": "p50 {{endpoint}}"
    }
   ]
  }
 ]
}